[versions]
poi = "5.2.5"
logback = "1.5.6"
slf4j = "2.0.13"
junit-jupiter = "5.12.1"
assertj = "3.26.3"
junit-platform = "1.12.0"

[libraries]
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
